Nhom6/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList; 
using PagedList.Mvc;
using Nhom6.Models;


namespace Nhom6.Controllers
{
    public class TrangChuController : Controller
    {
        QLNHDataContext data = new QLNHDataContext(); // Biến data quản lý CSDL
        private List<SanPham> LaySP()

        {
            return data.SanPhams.ToList(); // hàm trả về list table SanPham
        }

        public ActionResult Index(int? page) // Khi nhấn vào trang chủ hàm này sẽ kích hoạt
        {                                      //tham số page để chỉ ra số trang trong list sản phẩm ở trang chủ
            int SoSP = 9; // SoSP chỉ ra số sản phẩm sẽ hiển thị trên web, nếu quá hơn số sp sẽ tự phân thành trang kế tiếp             
            int SoTrang = (page ?? 1); //Chỉ ra số trang 

            var nh = LaySP(); //Lấy list sản phẩm có trong CSDL
            return View(nh.ToPagedList(SoTrang, SoSP)); //Trả về Model chứa table SanPham, chứa hàm phân trang có trong PagedList
        }

        public ActionResult Hang()
        {
            var hang = (from a in data.HangNHs select a).Take(12); //Lấy 12 Hãng
            return PartialView(hang);
        }


        public ActionResult SpHot(int i) // i là số sản phẩm sẽ bỏ qua để lấy các sản phẩm khác nhau trong carousel slide
        {
            var sp = (from a in data.SanPhams select a).Skip(i).Take(4); //Lấy 4 sản phẩm để hiển thị trong carousel slide
            return PartialView(sp); //Đây là PartialView của LayoutUser
        }
        public ActionResult LienHe()
        {
            return View();
        }
      
        public ActionResult ShowRoom()
        {
            return View();
        }
     
        public ActionResult ChoNam(int? pape)//trang cho nam            
        {
            var t = from a in data.SanPhams where (a.MaLoai == 1) select a;//truy vấn sql
            int SoSP = 9;//so sp trong 1 trang là 9
            int SoTrang = (pape ?? 1);
            return View(t.ToPagedList(SoTrang, SoSP));//trả về sp &trang

        }
        public ActionResult ChoNu(int? pape)//trang sp cho nữ
        {
            var t = from a in data.SanPhams where (a.MaLoai == 2) select a;//truy vấn lấy dữ liệu
            int SoSP = 9;//so sp trong 1 trang la 9
            int SoTrang = (pape ?? 1);
            return View(t.ToPagedList(SoTrang, SoSP));
        }
        public ActionResult SpHang(int? page,int id)//trang sp theo hãng
        {
            int SoSP = 9;
            int SoTrang = (page ?? 1);
            var sp = from a in data.SanPhams where (a.MaHang == id) select a;//truy vấn lấy id của hãng sp mới chọn
            var b = data.HangNHs.SingleOrDefault(n=>n.MaHang==id);
            ViewBag.Hang = b.TenHang;//khai báo viewbag cho tên hãng
            return View(sp.ToPagedList(SoTrang, SoSP));
        }
        public ActionResult chitiet(int id)
        {
            var ct = (from t in data.SanPhams where (t.MaNH == id) select t);//lấy id sản phẩm mới chọn để hiện chi tiết sp đó
            return View(ct.SingleOrDefault());
        }

    }
}

Nhom6/Views/TrangChu/ChoNam.cshtml
@using Nhom6.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>
    @{
        ViewBag.Title = "ChoNam";
        Layout = "~/Views/Shared/layoutUser.cshtml";
    }
    <br />
    <h3 style="margin-left: 25px;">Danh sách sản phẩm cho nam</h3>
    <br />
    <ul class="thumbnails">
        @foreach (var item in Model)
        {
            <li class="span3">
                <div class="thumbnail">
                    <i class="tag"></i>
                    <a href="@Url.Action("chitiet","TrangChu", new { id = item.MaNH })"><img src="@Url.Content("~/hinhsp/" + @item.hinh)" width="300"></a>
                    <div class="caption" style="height: 130px;">
                        <h5 style="height: 60px">@item.TenNH</h5>
                        <h4><a class="btn" href="@Url.Action("ThemGioHang", "GioHang", new { @iMANH=@item.MaNH , @strURL=Request.Url.ToString(), @sl=1})">Thêm Vào Giỏ</a> <span class="pull-right">@String.Format("{0:0,0 VNĐ}", @item.Gia).Replace(",", ".")</span></h4>
                    </div>
                </div>
            </li>
        }
    </ul>
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
    <div class="menutrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
    <style>
        .menutrang li {
            display: inline;
        }
    </style>

Nhom6/Views/TrangChu/ChoNu.cshtml
@using Nhom6.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>
    @{
        ViewBag.Title = "ChoNu";
        Layout = "~/Views/Shared/LayOutUser.cshtml";
    }
    <br />
    <h3 style="margin-left: 25px;">Danh sách sản phẩm cho nữ</h3>
    <br />
    <ul class="thumbnails">
        @foreach (var item in Model)
        {
            <li class="span3">
                <div class="thumbnail">
                    <i class="tag"></i>
                    <a href="@Url.Action("chitiet","TrangChu", new { id = item.MaNH })"><img src="@Url.Content("~/hinhsp/" + @item.hinh)" width="300"></a>
                    <div class="caption" style="height: 130px;">
                        <h5 style="height: 60px">@item.TenNH</h5>
                        <h4><a class="btn" href="@Url.Action("ThemGioHang", "GioHang", new { @iMANH=@item.MaNH , @strURL=Request.Url.ToString(), @sl=1})">Thêm Vào Giỏ</a> <span class="pull-right">@String.Format("{0:0,0 VNĐ}", @item.Gia).Replace(",", ".")</span></h4>
                    </div>
                </div>
            </li>
        }
    </ul>
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
    <div class="menutrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
    <style>
        .menutrang li {
            display: inline;
        }
    </style>

Nhom6/Views/TrangChu/Index.cshtml
@using Nhom6.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>
@{
 <title>Nước Hoa Nam Nữ || Chất Lượng</title>  <!-- Tiêu đề trang chủ -->
    Layout = "~/Views/Shared/LayOutUser.cshtml";<!-- Layout chung -->

}
<br />
<h3 style="margin-left: 25px;">Danh sách sản phẩm</h3>
<br />
<ul class="thumbnails">
    <!-- Danh sách tất cả sản phẩm lấy từ model được return từ TrangChuController hàm Index -->
    @foreach (var item in Model)
    {
        <li class="span3">
            <div class="thumbnail">
                <!-- Khung chứa sản phẩm-->
                <i class="tag"></i>
                <a href="@Url.Action("chitiet","TrangChu", new { id = item.MaNH })"><img src="@Url.Content("~/hinhsp/" + @item.hinh)" width="300"></a>
                <div class="caption" style="height: 130px;">
                    <h5 style="height: 60px">@item.TenNH</h5>
                    <!-- Button thêm giỏ hàng-->
                    <h4><a class="btn" href="@Url.Action("ThemGioHang", "GioHang", new { @iMANH=@item.MaNH , @strURL=Request.Url.ToString(), @sl=1})">Thêm Vào Giỏ</a> <span class="pull-right">@String.Format("{0:0,0 VNĐ}", @item.Gia).Replace(",", ".")</span></h4>
                </div>
            </div> <!--Kết thúc khung chứa sản phẩm-->
        </li>
    }
</ul>
<div style="text-align:center">
    <!-- Kết thúc danh sách sản phẩm -->
    @*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount*@    <!-- Số trang hiện tại -->
    <div class="menutrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))   <!-- Button để đi đến trang tiếp theo -->
    </div>
</div>

<style>
    .menutrang li {
        display: inline;
    }
</style>

Nhom6/Views/TrangChu/LienHe.cshtml
@{
<<<<<<< HEAD
    ViewBag.Title = "LienHe";
    Layout = "~/Views/Shared/layoutchung.cshtml";
}

<h3>Thông tin liên hệ</h3>
<hr class="soft" />
<br />

=======
    ViewBag.Title = "Lienhe";
    Layout = "~/Views/Shared/LayOutUser.cshtml";
}

<h3>Thông tin liên hệ</h3>
<!-- Do not change the code! -->
@*lấy mã nhúng từ trang foxyform , ng dùng gởi thông tin sẽ về email của trang đăng kí khi lấy mã nhúng*@

<a id="foxyform_embed_link_839256" href="http://www.foxyform.com/">foxyform</a>
<script type="text/javascript">
    (function (d, t) {
        var g = d.createElement(t),
            s = d.getElementsByTagName(t)[0];
        g.src = "http://www.foxyform.com/js.php?id=839256&sec_hash=e9fa6d989fd&width=350px";
        s.parentNode.insertBefore(g, s);
    }(document, "script"));
</script>
<!-- Do not change the code! -->
@*thêm thông tin người bán hàng*@
<div id="sidebar" class="span3" style="background-color:lightpink">
    <h4 style=" margin-left 5px;"> Nhung: 01636769370</h4>
    <h4 style=" margin-left 5px;"> Phương: 1090735648</h4>
    <h4 style=" margin-left 5px;"> Shipper: 8564864643</h4>
    <h4 style=" margin-left 5px;"> Trung tâm: 05688487</h4>
</div>
>>>>>>> CamNhung_Rose

Nhom6/Views/TrangChu/SpHang.cshtml
@using Nhom6.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>
    @{
        ViewBag.Title = "SpHang";
        Layout = "~/Views/Shared/LayOutUser.cshtml";
    }
    <br />
    <h3 style="margin-left: 25px;">@ViewBag.Hang</h3>
    <br />
    <ul class="thumbnails">
        @foreach (var item in Model)
        {
            <li class="span3">
                <div class="thumbnail">
                    <i class="tag"></i>
                    <a href="@Url.Action("chitiet","TrangChu", new { id = item.MaNH })"><img src="@Url.Content("~/hinhsp/" + @item.hinh)" width="300"></a>
                    <div class="caption" style="height: 130px;">
                        <h5 style="height: 60px">@item.TenNH</h5>
                        <h4><a class="btn" href="@Url.Action("ThemGioHang", "GioHang", new { @iMANH=@item.MaNH , @strURL=Request.Url.ToString(), @sl=1})">Thêm Vào Giỏ</a> <span class="pull-right">@String.Format("{0:0,0 VNĐ}", @item.Gia).Replace(",", ".")</span></h4>
                    </div>
                </div>
            </li>
        }
    </ul>
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
    <div class="menutrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
    <style>
        .menutrang li {
            display: inline;
        }
    </style>

Nhom6/Views/TrangChu/SpHot.cshtml
@model IEnumerable<Nhom6.Models.SanPham>


@{
//int i = 0;
}
<!-- Lấy tông tin tham thố truyền từ Layoutuser chỉ số i-->


@foreach (var item in Model)  //Chạy vòng lặp lấy sản phẩm hot
{


    <li class="span3">
        <div class="thumbnail">
            <!-- Khung chứa sản phẩm-->
            <i class="tag"></i> <!-- New-->
            <!-- Khi nhấn vào hình sản phẩm sẽ chuyển sang trang chi tiết sản phẩm-->
            <a href="@Url.Action("chitiet","TrangChu", new { id = item.MaNH })"><img src="@Url.Content("~/hinhsp/" + @item.hinh)" width="200"></a>
            <div class="caption" style="height: 100px;">
                <h5 style="height:50px;">@item.TenNH</h5><!--Lấy tên nước hoa trong model-->
                <!--Button chi tiết sp khi nhấn vào View-->
                <h4><a class="btn" href="@Url.Action("chitiet","TrangChu", new { id = item.MaNH })" style="">VIEW</a> <span class="pull-right">@String.Format("{0:0,0}", @item.Gia).Replace(",", ".") </span></h4> <!-- Giá sản phẩm lấy theo định dạng VNĐ-->
            </div>
        </div>
    </li>



}<!-- Hết vòng lặp-->

Nhom6/Views/TrangChu/TimKiem.cshtml
@using webfinal.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SanPham>
@{
    ViewBag.Title = "TimKiem";
    Layout = "~/Views/Shared/layoutchung.cshtml";
}

<br />
<h3 style="margin-left: 25px;">Danh sách sản phẩm bạn muốn tìm</h3>
<br />
<ul class="thumbnails">
    @foreach (var item in Model)
    {
        <li class="span3">
            <div class="thumbnail">
                <i class="tag"></i>
                <a href="@Url.Action("chitiet","TrangChu", new { id = item.MaNH })"><img src="@Url.Content("~/hinhsp/" + @item.hinh)" width="300"></a>
                <div class="caption" style="height: 130px;">
                    <h5 style="height: 60px">@item.TenNH</h5>
                    <h4><a class="btn" href="@Url.Action("ThemGioHang", "GioHang", new { @iMANH=@item.MaNH , @strURL=Request.Url.ToString(), @sl=1})">Thêm Vào Giỏ</a> <span class="pull-right">@String.Format("{0:0,0 VNĐ}", @item.Gia).Replace(",", ".")</span></h4>
                </div>
            </div>
        </li>
    }
</ul>
Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount
<div class="menutrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>
<style>
    .menutrang li {
        display: inline;
    }
</style>

Nhom6/Views/TrangChu/chitiet.cshtml
@{
    ViewBag.Title = "chitiet";
    Layout = "~/Views/Shared/LayOutUser.cshtml";
}
<div class="row">
    <div id="gallery" class="span3">
        <a href="@Url.Content("~/hinhsp/" + @Model.hinh)" title="Fujifilm FinePix S2950 Digital Camera">
            <img src="@Url.Content("~/hinhsp/" + @Model.hinh)" style="width:100%" alt="Fujifilm FinePix S2950 Digital Camera" />
        </a>
        <div id="differentview" class="moreOptopm carousel slide">
            <div class="carousel-inner">
                <div class="item active">
                    <a href="@Url.Content("~/hinhsp/" + @Model.hinh)"> <img style="width:29%" src="@Url.Content("~/hinhsp/" + @Model.MaNH + ".png")" alt=" " /></a>
                    <a href="@Url.Content("~/hinhsp/" + @Model.hinh)"> <img style="width:29%" src="@Url.Content("~/hinhsp/" + @Model.MaNH + ".png")" alt=" " /></a>
                    <a href="@Url.Content("~/hinhsp/" + @Model.hinh)"> <img style="width:29%" src="@Url.Content("~/hinhsp/" + @Model.MaNH + ".png")" alt=" " /></a>
                </div>
                <div class="item">
                    <a href="@Url.Content("~/hinhsp/" + @Model.hinh)"> <img style="width:29%" src="@Url.Content("~/hinhsp/" + @Model.MaNH + ".png")" alt=" " /></a>
                    <a href="@Url.Content("~/hinhsp/" + @Model.hinh)"> <img style="width:29%" src="@Url.Content("~/hinhsp/" + @Model.MaNH + ".png")" alt=" " /></a>
                    <a href="@Url.Content("~/hinhsp/" + @Model.hinh)"> <img style="width:29%" src="@Url.Content("~/hinhsp/" + @Model.MaNH + ".png")" alt=" " /></a>
                </div>
            </div>
            <!--
            <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
            <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
            -->
        </div>

        <div class="btn-toolbar">
            <div class="btn-group">
                <span class="btn"><i class="icon-envelope"></i></span>
                <span class="btn"><i class="icon-print"></i></span>
                <span class="btn"><i class="icon-zoom-in"></i></span>
                <span class="btn"><i class="icon-star"></i></span>
                <span class="btn"><i class=" icon-thumbs-up"></i></span>
                <span class="btn"><i class="icon-thumbs-down"></i></span>
            </div>
        </div>
    </div>

    <div class="span6">
        <h3>@Model.TenNH</h3>
        <small>@Model.PhongCach</small>
        <hr class="soft" />
        <form class="form-horizontal qtyFrm" method="post" action="@Url.Action("ThemGioHang", "GioHang", new { @iMANH = @Model.MaNH, @strURL = Request.Url.ToString(), @sl = 1 })">
            <div class="control-group">
                <label class="control-label"><span> @String.Format("{0:0,0 VNĐ}", Model.Gia).Replace(",", ".")</span></label>
                <div class="controls">
                    <input type="number" class="span1" placeholder="Qty." />
                    <button type="submit" class="btn btn-large btn-primary pull-right"> Thêm Vào Giỏ <i class=" icon-shopping-cart"></i></button>
                </div>
            </div>
        </form>

        <hr class="soft" />
        <h4>100 items in stock</h4>
        <hr class="soft clr" />
        <p>
            @Model.MoTa
        </p>
        <a class="btn btn-small pull-right" href="#detail">Xem Thêm</a>
        <br class="clr" />
        <a href="#" name="detail"></a>
        <hr class="soft" />
    </div>

    <div class="span9">
        <ul id="productDetail" class="nav nav-tabs">
            <li class="active"><a href="#home" data-toggle="tab">Chi Tiết Sản Phẩm</a></li>
            <li><a href="#profile" data-toggle="tab">Một Số Sản Phẩm Khác</a></li>
        </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade active in" id="home">
                <h4>Thông tin sản phẩm</h4>
                <table class="table table-bordered">
                    <tbody>
                        <tr class="techSpecRow"><th colspan="2">Product Details</th></tr>
                        <tr class="techSpecRow"><td class="techSpecTD1">Tên nước hoa: </td><td class="techSpecTD2">@Model.TenNH</td></tr>
                        <tr class="techSpecRow"><td class="techSpecTD1">Giá: </td><td class="techSpecTD2">@String.Format("{0:0,0 VNĐ}", Model.Gia).Replace(",", ".")</td></tr>
                        <tr class="techSpecRow"><td class="techSpecTD1">Nồng độ: :</td><td class="techSpecTD2">@Model.NongDo</td></tr>
                        <tr class="techSpecRow"><td class="techSpecTD1">Nhóm hương:</td><td class="techSpecTD2">@Model.NhomHuong</td></tr>
                        <tr class="techSpecRow"><td class="techSpecTD1">Phong cách:</td><td class="techSpecTD2">@Model.PhongCach</td></tr>
                        <tr class="techSpecRow"><td class="techSpecTD1">Năm sản xuất:</td><td class="techSpecTD2">@Model.NamSX</td></tr>
                        <tr class="techSpecRow"><td class="techSpecTD1">Xuất xứ:</td><td class="techSpecTD2">@Model.XuatXu</td></tr>
                        <tr class="techSpecRow"><td class="techSpecTD1">Phong cách:</td><td class="techSpecTD2">@Model.PhongCach</td></tr>
                    </tbody>
                </table>
                <h5>Mô Tả</h5>
                <p>
                    @Model.MoTa
                </p>
            </div>
            <div class="tab-pane fade" id="profile">
                <div id="myTab" class="pull-right">
                    <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
                    <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
                </div>
                <br class="clr" />
                <hr class="soft" />
                <div class="tab-content">
                    @Html.Action("SpKhac", "TrangChu")
                </div>
                <br class="clr">
            </div>
        </div>
    </div>
</div>

Nhom6/Views/TrangChu/dangky.cshtml
@{
    ViewBag.Title = "dangky";
    Layout = "~/Views/Shared/layoutchung.cshtml";
}
<ul class="breadcrumb">
    <li><a href="index.html">Home</a> <span class="divider">/</span></li>
    <li class="active">Registration</li>
</ul>
<h3> Đăng ký</h3>
<div class="well">
    <form class="form-horizontal" action="@Url.Action("DangKy", "TrangChu")" method="post">
        <h4>Hãy điền đầy đủ thông tin</h4>
            <div class="control-group">
                <label class="control-label" for="inputFname1">Họ Tên <sup>*</sup></label>
                <div class="controls">
                    <input type="text" id="inputFname1" placeholder="Họ Tên" name="HoTen"> <a style="color:red">@ViewData["loi1"]</a>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputLnam">Tên tài khoản <sup>*</sup></label>
                <div class="controls">
                    <input type="text" id="inputLnam" placeholder="Tên tài khoản" name="TK"> <a style="color:red">@ViewData["loi2"]</a>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputPassword">mật khẩu <sup>*</sup></label>
                <div class="controls">
                    <input type="text" id="input_email" placeholder="mật khẩu" name="MK"> <a style="color:red">@ViewData["loi3"]</a>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="inputPassword1">nhập lại mật khẩu<sup>*</sup></label>
                <div class="controls">
                    <input type="password" id="inputPassword1" placeholder="nhập lại mật khẩu" name="MK2"> <a style="color:red">@ViewData["loi4"]</a>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Ngày sinh<sup>*</sup></label>
                <div class="controls">
                    <input type="date" id="days" placeholder="ngày sinh" name="Ngaysinh"> <a style="color:red">@ViewData["loi5"]</a>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="company">Số điện thoại </label>
                <div class="controls">
                    <input type="text" id="company" placeholder="Số điện thoại" name="SDT" /> <a style="color:red">@ViewData["loi7"]</a>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="address">Địa chỉ<sup>*</sup></label>
                <div class="controls">
                    <input type="text" id="address" placeholder="Địa chỉ" name="DC" /> <a style="color:red">@ViewData["loi6"]</a>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label" for="input_email">Email<sup>*</sup></label>
                <div class="controls">
                    <input type="text" id="address2" placeholder="Email" name="Email" /> <a style="color:red">@ViewData["loi8"]</a>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <input class="btn btn-large btn-success" type="submit" value="Đăng Ký" />
                </div>
            </div>
        
    </form>

</div>